In [1]:
import pandas as pd

In [2]:
pledge = pd.read_csv('data/pledge_with_enddate_new.csv')

In [3]:
pledge.head()

,Unnamed: 0,股票代码,质押日期,股东名称,质押方,质押股数(万股),占所持股比例(%),占总股本比例(%),冻结事由,冻结期限,...,预警线(估算),平仓线(估算),质押日收盘价(前复权)(元),最新收盘价(元),质押股数(万股).1,占所持股比例(%).1,占总股本比例(%).1,解除日期,公告日期,平仓日
0,0,000034.SZ,2016/11/25,郭为,华福证券有限责任公司,"3,556.00",22.98,5.4367,"郭为将35,560,000股质押给华福证券有限责任公司","质押初始交易日是2016年11月25日,购回交易日是2019年6月14日,现在延期至2020...",...,17.8048,15.5792,27.82,14.15,"11,223.00",72.5104,17.16,2020/9/30,2019/8/13,20180619
1,1,000046.SZ,2016/2/2,中国泛海控股集团有限公司,兴业银行股份有限公司上海分行,"9,583.33",2.77,1.8400,质押给兴业银行股份有限公司上海分行,--,...,5.9100,5.1700,9.23,4.61,"277,068.83",80.08,53.32,2020/2/2,2016/2/5,20180704
2,2,000046.SZ,2016/2/2,中国泛海控股集团有限公司,兴业银行股份有限公司上海分行,"9,583.33",2.75,1.8400,"中国泛海控股集团有限公司质押给兴业银行股份有限公司上海分行95,833,333股",起始日期2012年2月2日,...,5.9100,5.1700,9.23,4.61,"339,517.71",97.57,65.34,--,2017/12/2,20180704
3,3,000056.SZ,2018/6/12,深圳市皇庭投资管理有限公司,安信证券股份有限公司,372.12,1.52,0.3200,"深圳市皇庭投资管理有限公司质押3,721,209股给安信证券股份有限公司用于补充质押。","质押开始日期2018年6月12日,质押到期日2019年11月2日",...,6.3600,5.5700,9.94,3.80,"24,216.59",98.17,20.6,2019/11/2,2018/6/14,20181214
4,4,000056.SZ,2018/5/9,深圳市皇庭投资管理有限公司,安信证券股份有限公司,325,1.32,0.2800,"深圳市皇庭投资管理有限公司质押3,250,000股给安信证券股份有限公司",质押期限从2018年5月9日至2019年11月2日,...,6.3900,5.5900,9.99,3.80,"24,117.47",97.77,20.52,2019/11/2,2018/5/12,20181206

In [4]:
pledge.columns

Index(['Unnamed: 0', '股票代码', '质押日期', '股东名称', '质押方', '质押股数(万股)', '占所持股比例(%)',
       '占总股本比例(%)', '冻结事由', '冻结期限', '状态', '预警线(估算)', '平仓线(估算)',
       '质押日收盘价(前复权)(元)', '最新收盘价(元)', '质押股数(万股).1', '占所持股比例(%).1',
       '占总股本比例(%).1', '解除日期', '公告日期', '平仓日'],
      dtype='object')

In [5]:
pledge = pledge.drop(['股东名称', '质押方', 
                      '冻结事由', '冻结期限', 
                      '最新收盘价(元)', '解除日期', 
                      '公告日期', '质押日期', 'Unnamed: 0'], axis=1)

In [6]:
pledge.head()

,股票代码,质押股数(万股),占所持股比例(%),占总股本比例(%),状态,预警线(估算),平仓线(估算),质押日收盘价(前复权)(元),质押股数(万股).1,占所持股比例(%).1,占总股本比例(%).1,平仓日
0,000034.SZ,"3,556.00",22.98,5.4367,已到平仓线,17.8048,15.5792,27.82,"11,223.00",72.5104,17.16,20180619
1,000046.SZ,"9,583.33",2.77,1.8400,已到平仓线,5.9100,5.1700,9.23,"277,068.83",80.08,53.32,20180704
2,000046.SZ,"9,583.33",2.75,1.8400,已到平仓线,5.9100,5.1700,9.23,"339,517.71",97.57,65.34,20180704
3,000056.SZ,372.12,1.52,0.3200,已到平仓线,6.3600,5.5700,9.94,"24,216.59",98.17,20.6,20181214
4,000056.SZ,325,1.32,0.2800,已到平仓线,6.3900,5.5900,9.99,"24,117.47",97.77,20.52,20181206

In [7]:
pledge.columns

Index(['股票代码', '质押股数(万股)', '占所持股比例(%)', '占总股本比例(%)', '状态', '预警线(估算)',
       '平仓线(估算)', '质押日收盘价(前复权)(元)', '质押股数(万股).1', '占所持股比例(%).1', '占总股本比例(%).1',
       '平仓日'],
      dtype='object')

In [8]:
pledge = pledge.rename(columns = {
    '股票代码': 'code',
    '质押股数(万股)': 'this_pledge_nb',
    '占所持股比例(%)': 'this_share_ratio',
    '占总股本比例(%)': 'this_stock_ratio',
    '状态': 'status',
    '预警线(估算)': 'alarm_line',
    '平仓线(估算)': 'close_position_line',
    '质押日收盘价(前复权)(元)': 'price_on_pledge',
    '质押股数(万股).1': 'total_pledge_nb',
    '占所持股比例(%).1': 'total_share_ratio',
    '占总股本比例(%).1': 'total_stock_ratio',
    '平仓日': 'close_position_date'
})

In [9]:
pledge.head()

,code,this_pledge_nb,this_share_ratio,this_stock_ratio,status,alarm_line,close_position_line,price_on_pledge,total_pledge_nb,total_share_ratio,total_stock_ratio,close_position_date
0,000034.SZ,"3,556.00",22.98,5.4367,已到平仓线,17.8048,15.5792,27.82,"11,223.00",72.5104,17.16,20180619
1,000046.SZ,"9,583.33",2.77,1.8400,已到平仓线,5.9100,5.1700,9.23,"277,068.83",80.08,53.32,20180704
2,000046.SZ,"9,583.33",2.75,1.8400,已到平仓线,5.9100,5.1700,9.23,"339,517.71",97.57,65.34,20180704
3,000056.SZ,372.12,1.52,0.3200,已到平仓线,6.3600,5.5700,9.94,"24,216.59",98.17,20.6,20181214
4,000056.SZ,325,1.32,0.2800,已到平仓线,6.3900,5.5900,9.99,"24,117.47",97.77,20.52,20181206

In [10]:
pledge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 12 columns):
code                   1002 non-null object
this_pledge_nb         1002 non-null object
this_share_ratio       1002 non-null float64
this_stock_ratio       1002 non-null float64
status                 1002 non-null object
alarm_line             1002 non-null float64
close_position_line    1002 non-null float64
price_on_pledge        1002 non-null float64
total_pledge_nb        1001 non-null object
total_share_ratio      1001 non-null object
total_stock_ratio      1001 non-null object
close_position_date    1002 non-null object
dtypes: float64(5), object(7)
memory usage: 94.1+ KB

In [11]:
pledge['total_pledge_nb'] = pledge['total_pledge_nb'].apply(lambda x: str(x).replace(',', ''))

In [12]:
import numpy as np
for i in range(pledge.shape[0]):
    for j in range(pledge.shape[1]):
        if pledge.iloc[i, j] == '--':
            pledge.iloc[i, j] = np.nan

In [13]:
na_columns = ['total_pledge_nb', 'total_share_ratio', 'total_stock_ratio', 'this_pledge_nb']
for col in na_columns:
    pledge[col] = pd.to_numeric(pledge[col], errors='coerce')
    pledge[col] = pledge[col].fillna(pledge[col].mean())

In [14]:
pledge.head()

,code,this_pledge_nb,this_share_ratio,this_stock_ratio,status,alarm_line,close_position_line,price_on_pledge,total_pledge_nb,total_share_ratio,total_stock_ratio,close_position_date
0,000034.SZ,350.94729,22.98,5.4367,已到平仓线,17.8048,15.5792,27.82,11223.00,72.5104,17.16,20180619
1,000046.SZ,350.94729,2.77,1.8400,已到平仓线,5.9100,5.1700,9.23,277068.83,80.0800,53.32,20180704
2,000046.SZ,350.94729,2.75,1.8400,已到平仓线,5.9100,5.1700,9.23,339517.71,97.5700,65.34,20180704
3,000056.SZ,372.12000,1.52,0.3200,已到平仓线,6.3600,5.5700,9.94,24216.59,98.1700,20.60,20181214
4,000056.SZ,325.00000,1.32,0.2800,已到平仓线,6.3900,5.5900,9.99,24117.47,97.7700,20.52,20181206

In [15]:
pledge['status'] = pledge['status'].apply(lambda x: 1)

In [16]:
pledge.head()

,code,this_pledge_nb,this_share_ratio,this_stock_ratio,status,alarm_line,close_position_line,price_on_pledge,total_pledge_nb,total_share_ratio,total_stock_ratio,close_position_date
0,000034.SZ,350.94729,22.98,5.4367,1,17.8048,15.5792,27.82,11223.00,72.5104,17.16,20180619
1,000046.SZ,350.94729,2.77,1.8400,1,5.9100,5.1700,9.23,277068.83,80.0800,53.32,20180704
2,000046.SZ,350.94729,2.75,1.8400,1,5.9100,5.1700,9.23,339517.71,97.5700,65.34,20180704
3,000056.SZ,372.12000,1.52,0.3200,1,6.3600,5.5700,9.94,24216.59,98.1700,20.60,20181214
4,000056.SZ,325.00000,1.32,0.2800,1,6.3900,5.5900,9.99,24117.47,97.7700,20.52,20181206

In [18]:
pledge['close_position_date'] = pledge['close_position_date'].apply(lambda x: x[:4] + '-' + x[4:6] + '-' + x[6:])

In [21]:
pledge = pledge.drop([809])

In [22]:
pledge['close_position_date'] = pd.to_datetime(pledge['close_position_date'])

In [23]:
pledge.head()

,code,this_pledge_nb,this_share_ratio,this_stock_ratio,status,alarm_line,close_position_line,price_on_pledge,total_pledge_nb,total_share_ratio,total_stock_ratio,close_position_date
0,000034.SZ,350.94729,22.98,5.4367,1,17.8048,15.5792,27.82,11223.00,72.5104,17.16,2018-06-19
1,000046.SZ,350.94729,2.77,1.8400,1,5.9100,5.1700,9.23,277068.83,80.0800,53.32,2018-07-04
2,000046.SZ,350.94729,2.75,1.8400,1,5.9100,5.1700,9.23,339517.71,97.5700,65.34,2018-07-04
3,000056.SZ,372.12000,1.52,0.3200,1,6.3600,5.5700,9.94,24216.59,98.1700,20.60,2018-12-14
4,000056.SZ,325.00000,1.32,0.2800,1,6.3900,5.5900,9.99,24117.47,97.7700,20.52,2018-12-06

In [27]:
pledge['is_st'] = pledge.apply(lambda x: 1 if 'ST' in x.code else 0, axis=1)

In [29]:
pledge['code'] = pledge['code'].apply(lambda x: x[2:] if 'ST' in x else x)

In [31]:
pledge.loc[351]

code                             000892.SZ
this_pledge_nb                     350.947
this_share_ratio                     48.32
this_stock_ratio                      2.42
status                                   1
alarm_line                           10.12
close_position_line                   8.85
price_on_pledge                      15.81
total_pledge_nb                       1000
total_share_ratio                    48.32
total_stock_ratio                     2.42
close_position_date    2017-08-08 00:00:00
is_st                                    0
Name: 351, dtype: object

In [32]:
pledge.head()

,code,this_pledge_nb,this_share_ratio,this_stock_ratio,status,alarm_line,close_position_line,price_on_pledge,total_pledge_nb,total_share_ratio,total_stock_ratio,close_position_date,is_st
0,000034.SZ,350.94729,22.98,5.4367,1,17.8048,15.5792,27.82,11223.00,72.5104,17.16,2018-06-19,0
1,000046.SZ,350.94729,2.77,1.8400,1,5.9100,5.1700,9.23,277068.83,80.0800,53.32,2018-07-04,0
2,000046.SZ,350.94729,2.75,1.8400,1,5.9100,5.1700,9.23,339517.71,97.5700,65.34,2018-07-04,0
3,000056.SZ,372.12000,1.52,0.3200,1,6.3600,5.5700,9.94,24216.59,98.1700,20.60,2018-12-14,0
4,000056.SZ,325.00000,1.32,0.2800,1,6.3900,5.5900,9.99,24117.47,97.7700,20.52,2018-12-06,0

In [33]:
pledge.to_csv('data/pledge_clean.csv')